apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-demo-2-configmap
  namespace: nginx
data:
  nginx.conf: |
    events {
      worker_connections  1024;
    }

    http {
      server {
        listen 80;
        server_name  _;
          location / {
            root /usr/share/nginx/html;
            index index.html;
          }
      }
    }
