- hosts: "{{ hosts }}"

  tasks:

    - name: Copy Docker Compose files
      copy:
        src: "{{ local_project_dir }}/{{ item }}"
        dest: "{{ remote_project_dir }}/{{ item }}"
      loop:
        - docker-compose.yaml

    - name: deploy Docker Compose stack
      community.docker.docker_compose_v2:
        project_src: "{{ remote_project_dir }}"
        files:
          - docker-compose.yaml
        state: present
