apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: authentik-eval-2-certificate
  namespace: authentik
spec:
  secretName: authentik-eval-2-tls
  issuerRef:
    name: certmanager-demo-1-clusterissuer
    kind: ClusterIssuer
  dnsNames:
    - authentik-eval-2.kube-demo-1.home.clcreative.de
