---
services:
  netbird:
    image: netbirdio/netbird:latest
    container_name: netbird-eval-1
    hostname: srv-demo-1.home.clcreative.de
    cap_add:
      - NET_ADMIN
      - SYS_ADMIN
      - SYS_RESOURCE
    environment:
      - NB_SETUP_KEY=${SETUP_KEY}
    volumes:
      - netbird-client:/etc/netbird
    restart: unless-stopped
volumes:
  netbird-client:
    name: netbird-client
