version: v3
teleport:
  nodename: teleport-demo-1.srv-prod-1.home.clcreative.de
  data_dir: /var/lib/teleport
  log:
    output: stderr
    severity: INFO
    format:
      output: text
  # ca_pin: ""
  # diag_addr: ""
auth_service:
  enabled: yes
  listen_addr: 0.0.0.0:3025
  proxy_listener_mode: multiplex
  cluster_name: teleport-demo-1.srv-prod-1.home.clcreative.de
  # ---
  # (Optional) Passwordless Authentication
  # authentication:
  #   type: local
  #   second_factor: on
  #   webauthn:
  #     rp_id: teleport-demo-1.srv-prod-1.home.clcreative.de
  #   connector_name: passwordless
  # ---
ssh_service:
  enabled: no
  # commands:
  # - name: hostname
  #   command: [hostname]
  #   period: 1m0s
proxy_service:
  enabled: yes
  web_listen_addr: 0.0.0.0:3080
  public_addr: teleport-demo-1.srv-prod-1.home.clcreative.de
  https_keypairs: []
  acme: {}
  # ---
  # (Optional) ACME
  # acme:
  #   enabled: yes
  #   email: your-email-address
  # ---
