---
services:
  gitlab:
    image: gitlab/gitlab-ce:17.0.1-ce.0
    container_name: gitlab-eval-1
    hostname: 'gitlab-eval-1.srv-prod-1.home.clcreative.de'
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        # Add any other gitlab.rb configuration here, each on its own line
        external_url 'https://gitlab-eval-1.srv-prod-1.home.clcreative.de'
    ports:
      - '80:80'
      - '443:443'
      - '2424:22'
    volumes:
      - ./config:/etc/gitlab
      - ./logs:/var/log/gitlab
      - ./data:/var/opt/gitlab
    shm_size: '256m'
    networks:
      - frontend
    labels:
      - traefik.enable=true
      - traefik.http.routers.gitlab-eval-1.rule=Host(`gitlab-eval-1.srv-prod-1.home.clcreative.de`)
      - traefik.http.routers.gitlab-eval-1.entrypoints=websecure
      - traefik.http.routers.gitlab-eval-1.tls=true
      - traefik.http.routers.gitlab-eval-1.tls.certresolver=cloudflare
    restart: unless-stopped

networks:
  frontend:
    external: true
