name: "Update DNS Records Testing with local webhook"

on:
  push:
    branches:
      - twingate_research-1
    paths:
      - 'dns/dns-prod-1/terraform/*.tf'
  workflow_dispatch:
  
defaults:
  run:
    working-directory: dns/dns-prod-1/terraform

jobs:
  send_dns_update:
    runs-on: ubuntu-latest
    steps:
      - name: Connect to Twingate
        uses: Twingate/github-action@V1.1
        with:
          service-key: ${{ secrets.GH_ACTIONS_TOKEN_1 }}

      - name: Install Curl
        run: sudo apt-get install -y curl

      - name: Send DNS Update Webhook
        run: |
          curl https://kestra-demo-1.srv-prod-1.home.clcreative.de/api/v1/executions/webhook/homelab.dns/dns-update-test/hTZVPMio9iJemDQeE8cX7y6KmweQdKsRMnrHRDvQDowMWmtkyZT223Abq38Fw4Le
